In [17]:
# Loading + inspection of data before cleaning, filtering.

In [32]:
# Read_csv - loading with right options
import pandas as pd
df_metrics = pd.read_csv(
    "server_metrics.csv", 
    parse_dates = ["timestamp"],
    dtype = {"server_id" : "category"},
    na_values = ["N/A", "null", "-"]
)
print("shows exact columns names :", df_metrics.columns.tolist(), "\n")
# head() and tail() - first and last look
print("top 5 rows of df_metrics", df_metrics.head())
print("last 5 rows of df_metrics", df_metrics.tail())

shows exact columns names : ['timestamp', 'server_id', 'cpu_pct', 'memory_pct', 'response_ms', 'disk_pct', 'status']

top 5 rows of df_metrics    timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct status
0 2026-01-01    srv-01     49.6        94.6        891.8      68.9     ok
1 2026-01-01    srv-02     32.3        33.9       1046.1      69.1     ok
2 2026-01-01    srv-03     21.6        96.0       1007.3      43.8     ok
3 2026-01-01    srv-04     34.5        50.7        653.5      58.1     ok
4 2026-01-01    srv-05     68.3        39.5        386.0      53.8     ok
last 5 rows of df_metrics               timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct  \
495 2026-01-05 03:00:00    srv-01     88.7        38.9        959.1      38.1
496 2026-01-05 03:00:00    srv-02     41.8        89.6       1135.6      39.7
497 2026-01-05 03:00:00    srv-03     97.5        62.9       1043.1      68.3
498 2026-01-05 03:00:00    srv-04     42.6        43.8        926.1      55.1
499 2026-01-05 03:00:00    srv-05     58.9        69.3       1045.4      93.7

      status
495  warning
496       ok
497       ok
498       ok
499       ok

In [31]:
# head()  0 see the structure
df_metrics.head()

,timestamp,server_id,cpu_pct,memory_pct,response_ms,disk_pct,status
0,2026-01-01 00:00:00,srv-01,49.6,94.6,891.8,68.9,ok
1,2026-01-01 00:00:00,srv-02,32.3,33.9,1046.1,69.1,ok
2,2026-01-01 00:00:00,srv-03,21.6,96.0,1007.3,43.8,ok
3,2026-01-01 00:00:00,srv-04,34.5,50.7,653.5,58.1,ok
4,2026-01-01 00:00:00,srv-05,68.3,39.5,386.0,53.8,ok

In [19]:
# shape - know the size
print(df_metrics.shape)

(500, 7)

In [20]:
# info() - inspection command - dtype - nulls
df_metrics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    500 non-null    datetime64[ns]
 1   server_id    500 non-null    category
 2   cpu_pct      500 non-null    float64
 3   memory_pct   500 non-null    float64
 4   response_ms  500 non-null    float64
 5   disk_pct     500 non-null    float64
 6   status       500 non-null    object
dtypes: category(1), datetime64[ns](1), float64(4), object(1)
memory usage: 24.1+ KB

In [21]:
# describe() - gives stastical summary
df_metrics.describe()

                 timestamp     cpu_pct  memory_pct  response_ms    disk_pct
count                  500  500.000000  500.000000   500.000000  500.000000
mean   2026-01-03 01:30:00   60.027400   63.355000   625.533600   62.412800
min    2026-01-01 00:00:00   20.600000   30.200000    51.800000   30.300000
25%    2026-01-02 00:45:00   39.000000   45.075000   335.950000   46.700000
50%    2026-01-03 01:30:00   60.900000   64.300000   633.700000   62.300000
75%    2026-01-04 02:15:00   81.300000   80.125000   908.125000   78.625000
max    2026-01-05 03:00:00   98.600000   98.000000  1196.400000   94.800000
std                    NaN   23.464233   20.007543   325.294967   18.823192

In [22]:
# isnull().sum() For percentage of nulls per column - null map
df_metrics.isnull().sum()

timestamp      0
server_id      0
cpu_pct        0
memory_pct     0
response_ms    0
disk_pct       0
status         0
dtype: int64

In [23]:
# value_counts() - category distribution
df_metrics["server_id"].value_counts()

server_id
srv-01    100
srv-02    100
srv-03    100
srv-04    100
srv-05    100
Name: count, dtype: int64

In [24]:
# statue distribution across fleet of servers
df_metrics["status"].value_counts(normalize=True).mul(100).round(1)
# NOrmalize gives percentages

status
ok          76.6
warning     17.8
critical     5.6
Name: proportion, dtype: float64

In [25]:
# nuniquye() - unique value counts
df_metrics.nunique()

timestamp      100
server_id        5
cpu_pct        371
memory_pct     356
response_ms    495
disk_pct       354
status           3
dtype: int64

In [33]:
# time range
df_metrics["timestamp"].agg(["min", "max"])

min   2026-01-01 00:00:00
max   2026-01-05 03:00:00
Name: timestamp, dtype: datetime64[ns]

In [26]:
# sample() - random cross section
df_metrics.sample(5) # 5 random rows
df_metrics.sample(frac=0.01) # 1 percent random sample

,timestamp,server_id,cpu_pct,memory_pct,response_ms,disk_pct,status
473,2026-01-04 22:00:00,srv-04,23.5,38.4,692.4,52.3,ok
258,2026-01-03 03:00:00,srv-04,51.4,39.0,702.7,74.8,warning
67,2026-01-01 13:00:00,srv-03,23.2,88.2,859.2,60.8,ok
160,2026-01-02 08:00:00,srv-01,75.9,40.4,712.7,69.4,ok
91,2026-01-01 18:00:00,srv-02,58.9,30.8,589.0,33.7,ok

In [27]:
# check column names - tolist()
df_metrics = pd.read_csv("server_metrics.csv")
print(df_metrics.columns.tolist())

['timestamp', 'server_id', 'cpu_pct', 'memory_pct', 'response_ms', 'disk_pct', 'status']

In [34]:
# Loading data, write to postgreSQL and read back required data through sql query in pandas. No CSV export needed.

import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("server_metrics.csv")
df["timestamp"] = pd.to_datetime(df["timestamp"])

engine = create_engine("postgresql://postgres:postgres@localhost:5432/postgres")

df.to_sql("server_metrics", engine, if_exists="replace", index=False)
#if_exists="replace" drops and recreates the table every run 

df_output = pd.read_sql("""
    SELECT server_id, timestamp, cpu_pct, memory_pct, response_ms
    FROM server_metrics
    WHERE timestamp >= (
        SELECT MAX(timestamp) - INTERVAL '7 days'
        FROM server_metrics
    )
""", engine)
print(df_output.dtypes)
print(df_output.max())
print(f" Date range : {df_output['timestamp'].min()} to {df_output['timestamp'].max()}")
print(f" Row count : {len(df_output)}")
print(f" Max CPU : {df_output['cpu_pct'].max()}")
print(df_output.head())

server_id              object
timestamp      datetime64[ns]
cpu_pct               float64
memory_pct            float64
response_ms           float64
dtype: object
server_id                   srv-05
timestamp      2026-01-05 03:00:00
cpu_pct                       98.6
memory_pct                    98.0
response_ms                 1196.4
dtype: object
 Date range : 2026-01-01 00:00:00 to 2026-01-05 03:00:00
 Row count : 500
 Max CPU : 98.6
  server_id  timestamp  cpu_pct  memory_pct  response_ms
0    srv-01 2026-01-01     49.6        94.6        891.8
1    srv-02 2026-01-01     32.3        33.9       1046.1
2    srv-03 2026-01-01     21.6        96.0       1007.3
3    srv-04 2026-01-01     34.5        50.7        653.5
4    srv-05 2026-01-01     68.3        39.5        386.0